### PR TITLE
Created docker-compose.yml

### PR DESCRIPTION
**Pull request by Mikerad1**
Created the docker-compose.yml file that will create the forum service, the postgres db and the pgAdmin to have a GUI for the db.

To connect from pgAdmin to the db, use db as the host name and you will be able to connect.

### CODE REVIEW

**Comment by fcgl** [comment]
is `docker-compose up --build` the command I need to run? Or is it something else?

**Comment by Mikerad1** [comment]
either `docker-compose up` or `docker stack deploy -c docker-compose.yml forum` though i prefer the latter as you can set up loadbalancing things with it

**Comment by Mikerad1** [comment]
though you do need the forum service image already built in your local docker repository

**Comment by fcgl** [comment]
Cool, will take a look at this now

**Comment by fcgl** [comment]
> though you do need the forum service image already built in your local docker repository

So run Dockerfile first then `docker stack deploy -c docker-compose.yml forum`?

**Comment by Mikerad1** [comment]
yea. in the location where the docker-compose file resides

**Comment by fcgl** [comment]
How exactly do I test this? How do I connect it to pgadmin for example? Or have postgres in the terminal?

**Comment by Mikerad1** [comment]
to test, you can open the microservice health url on port 8082, pgadmin on port 9000 and from pgadmin connect to the db by using the host name db

**Comment by Mikerad1** [comment]
default db account details are in the compose file

**Comment by fcgl** [comment]
Wow this is so cool! 💃

**Comment by Mikerad1** [comment]
haha yea. wanted to add a visualizer so you could watch like the "health" of the services but first wanted to get this out so that there can be a db and not be a blocker

**Review by fcgl — APPROVED** [review]
Looks good to me ✅

Will have to update https://github.com/fcgl/workbench to run this file after build. Or perhaps there is a best practice on how to do that. Will look into it. 

Great work! 😄

**Comment by Mikerad1** [comment]
can have it rebuild the docker file everytime you start the services but then it will probably download the maven stuff and stuff everytime which could chow data

**Comment by Mikerad1** [comment]
or you could modify that compose file to start each of the microservices db when it run with 1 pgadmin running so that you can connect to all the db's from there

**Comment by fcgl** [comment]
> or you could modify that compose file to start each of the microservices db when it run with 1 pgadmin running so that you can connect to all the db's from there

Yeah 1 pgadmin with each microservice db sounds good. Just gotta figure out how to do it. Will be on my trello board for next week

**Comment by Mikerad1** [comment]
all you will have to do is like i did with the db in this compose, but just like 4 of them with each service on its own port and pointing to their own volume

**Pull request merged**
